-- Gerado por node scripts/sync-enem-story.cjs. Execute no SQL Editor de um banco já configurado.
-- Atualiza somente a história; preserva questões complementares, tentativas, XP e progresso.
begin;
update public.rooms set story='A energia do setor principal foi desligada. Um terminal continua funcionando utilizando energia de emergência. O reservatório cilíndrico mantém os agentes vivos, mas a missão ainda vai durar dez dias. O terminal exige um plano de racionamento antes de liberar o reator.', description='O coração elétrico do laboratório. Um único terminal ainda responde.', difficulty='intermediario' where id='sala-01';
update public.rooms set story='Uma caixa utilizada para transportar equipamentos apresenta sinais de contaminação. Dentro dela estão cinco projetos de um tanque aberto de descontaminação. Todos guardam a mesma quantidade de solução, mas a equipe tem pouco revestimento de proteção. Compare os projetos e informe a menor área necessária para proteger o fundo e as quatro paredes internas.', description='Caixas de transporte lacradas. Uma delas pulsa com uma substância escura.', difficulty='intermediario' where id='sala-02';
update public.rooms set story='A sala está gelada. Uma luz azul fraca reflete no recipiente de isolamento. O monitor ainda mostra: SUBJECT CONNECTION: LOST. A equipe precisa fabricar um reservatório cilíndrico a partir de uma chapa retangular. A mesma chapa pode ser enrolada de duas maneiras; o desperdício de capacidade pode custar a conexão com a cobaia.', description='Água salgada, escuridão total e um recipiente que guarda mais do que líquido.', difficulty='dificil' where id='sala-03';
update public.rooms set story='No centro da câmara existe um núcleo de contenção fabricado a partir de um cone maciço. O topo foi cortado paralelamente à base e uma passagem cilíndrica atravessa a peça pelo eixo central. O sensor da balança exige a massa que sobrou após os dois cortes. A densidade do material está no relatório técnico.', description='Uma máquina geométrica ainda vibra. Ninguém sabe o que ela amplifica.', difficulty='dificil' where id='sala-04';
update public.rooms set story='Através do vidro, sensores esféricos flutuam presos por cabos. A nova rede usa sensores com o dobro do diâmetro anterior. A fábrica precisa saber quantas cargas de material serão necessárias para produzir o novo lote.', description='Um observatório dimensional apontado para baixo. Para o subsolo.', difficulty='dificil' where id='sala-05';
update public.rooms set story='O ar fica pesado. Partículas flutuam como cinzas. Raízes atravessam as paredes. O mecanismo do portal está sem rolamentos. Uma peça cilíndrica maciça do reator pode ser fundida para fabricar as pequenas esferas de reposição. “Nada pode se perder na fundição. O volume do metal antes e depois precisa ser o mesmo.” Determine quantos rolamentos podem ser produzidos e recupere o crachá preso nas raízes.', description='As paredes estão vivas. Raízes escuras atravessam o concreto.', difficulty='dificil' where id='sala-06';
update public.rooms set story='Uma rachadura vermelha se abre na parede de concreto. Entre as raízes, um último documento do cientista desaparecido.', description='A ruptura. A passagem que nunca deveria ter sido aberta.', difficulty='dificil' where id='portal';
update public.evidences set content='Cartão de nível 07 pertencente ao Dr. M. Ellison. No verso: “Registre a economia diária por agente. Essa reserva é a primeira chave.”', tag='RESERVA' where id='ev-001';
update public.evidences set content='“Registre a menor área de revestimento interno. Proteja o fundo e as paredes; a abertura superior deve permanecer livre.”', tag='REVESTIMENTO' where id='ev-002';
update public.evidences set content='[CHIADO] “...a cobaia diz ouvir alguém do outro lado... ela descreveu um corredor igual ao nosso, mas escuro... coberto de raízes...” [FIM DA GRAVAÇÃO]', tag=null where id='ev-003';
update public.evidences set content='“Registre a massa restante do núcleo, em gramas. Às 03:11 a leitura dimensional ultrapassou o limite. Recomendo encerrar o Experimento 011.”', tag='EXPERIMENTO' where id='ev-004';
update public.evidences set content='LAT 39.9°N  //  PROF. −40m  //  ORIGEM DO SINAL: SUB-NÍVEL 3. “Não é um eco. Algo responde.”', tag=null where id='ev-005';
update public.evidences set content='DR. MARCUS ELLISON — PESQUISADOR CHEFE — IDENTIFICAÇÃO: 7B. “Se ele está aqui, eu estou do outro lado.”', tag='IDENTIFICAÇÃO' where id='ev-006';
update public.evidences set content='“Se você encontrou isso, o experimento não acabou. Apenas conseguimos fechar o primeiro portal.” — M.E.', tag=null where id='ev-007';
insert into public.challenges (id, room_id, title, story, question, content, type, difficulty, xp_reward, hint, correct_answer, tolerance, evidence_id, next_room_id, order_index, active) values
('c-01','sala-01','Racionamento do Reator','A reserva deve sustentar 75 agentes durante os próximos 10 dias.','Restam 1,5 m de água em um reservatório cilíndrico de raio 5 m. Cada um dos 75 agentes consome normalmente 200 litros por dia. Sem novo abastecimento e sem perdas, qual é a economia mínima, em litros por agente por dia, para a reserva durar 10 dias? Use π = 3.','Volume, conversão de unidades e consumo diário. Informe apenas a economia por agente.','numeric','intermediario',20,'Calcule πr²h e converta de m³ para litros (1 m³ = 1.000 L). Divida pelos agentes e pelos dias para obter o consumo permitido. Subtraia esse consumo dos 200 L habituais.','50',0,'ev-001','sala-02',1,true),
('c-02','sala-02','Revestimento de Descontaminação','Os cinco tanques são abertos e comportam 90.000 litros cada. Somente o fundo e as paredes internas receberão proteção.','Compare os cinco projetos abaixo. Qual é a menor área de revestimento, em m², necessária para o fundo e as quatro paredes de um tanque? Desconsidere espessuras e perdas. As medidas estão na ordem profundidade × largura × comprimento.','Compare os projetos pela área interna. A abertura superior não recebe revestimento.','numeric','intermediario',20,'Para cada projeto, use A = largura·comprimento + 2·profundidade·(largura + comprimento). O volume ser igual não significa que a área também seja igual.','101',0,'ev-002','sala-03',2,true),
('c-03','sala-03','Dois Moldes, Uma Chapa','Uma chapa retangular forma somente a parede lateral do reservatório. As bases circulares são fabricadas separadamente.','Uma chapa de 12 cm por 24 cm pode ser enrolada de duas maneiras: altura 24 cm e circunferência 12 cm, ou altura 12 cm e circunferência 24 cm. Sem sobreposição nem perdas, qual é a maior capacidade, em cm³, entre os dois cilindros fechados? Use π = 3.','O lado que envolve a base é uma circunferência, não um diâmetro.','numeric','dificil',30,'Em cada orientação, obtenha o raio com C = 2πr e calcule V = πr²h. Compare os volumes antes de escolher.','576',0,'ev-003','sala-04',3,true),
('c-04','sala-04','Massa do Núcleo Perfurado','O corte do topo é paralelo à base. O furo cilíndrico atravessa todo o tronco e tem o mesmo eixo do cone original.','Um cone maciço tem altura 36 cm e base de diâmetro 18 cm. Retira-se seu topo, um cone menor de diâmetro 6 cm, e perfura-se o tronco restante com um cilindro de diâmetro 6 cm. O material tem densidade 0,6 g/cm³. Qual é a massa restante, em gramas? Use π = 3 e determine a altura do corte por semelhança.','Semelhança de cones, subtração de volumes e relação entre massa e densidade.','numeric','dificil',30,'A razão entre as alturas dos cones é igual à razão entre seus raios. Subtraia do cone original o cone menor e o cilindro cujo comprimento é a altura do tronco. Multiplique o volume que sobrar pela densidade.','1296',0,'ev-004','sala-05',4,true),
('c-05','sala-05','Ampliação da Rede de Sensores','Cada carga de material produz 50 sensores esféricos maciços de diâmetro 2 cm.','A nova rede precisa de 150 sensores maciços de diâmetro 4 cm, feitos do mesmo material. Sem perdas de fabricação, quantas cargas completas de material são necessárias?','Alterar o diâmetro muda o volume e o rendimento de cada carga.','numeric','dificil',30,'O volume varia com o cubo do raio. Compare os dois diâmetros, eleve a razão ao cubo e considere também que o número de sensores mudou.','24',0,'ev-005','sala-06',5,true),
('c-06','sala-06','Rolamentos de Contenção','Uma peça cilíndrica maciça será completamente fundida em pequenas esferas do mesmo material.','Uma peça de raio 4 cm e altura 50 cm será transformada em esferas maciças de diâmetro 1 cm. Admitindo conservação do volume e nenhuma perda de material, quantos rolamentos esféricos podem ser fabricados?','A quantidade produzida depende da relação entre os volumes dos dois sólidos.','numeric','dificil',30,'Divida V cilindro = πr²h por V esfera = (4/3)πr³. O raio da esfera é metade do diâmetro. O fator π se cancela.','4800',0,'ev-006','portal',6,true),
('f-011','portal','Protocolo 011','Reserva. Revestimento. Experimento. Identificação.','Qual é a sequência final que fecha o portal?','Cada palavra corresponde a um registro marcado nas suas evidências.','code','dificil',100,'Procure os carimbos nas evidências e concatene seus registros na ordem do documento, sem unidades nem zeros decimais extras. Separe os registros com hífens, se preferir.','5010112967B',0,'ev-007',null,7,true)
on conflict (id) do update set title=excluded.title, story=excluded.story, question=excluded.question, content=excluded.content, type=excluded.type, difficulty=excluded.difficulty, xp_reward=excluded.xp_reward, hint=excluded.hint, correct_answer=excluded.correct_answer, tolerance=excluded.tolerance, evidence_id=excluded.evidence_id, next_room_id=excluded.next_room_id;
commit;
